### ISSUE TITLE
Can't use method return value in write context

### ISSUE THREAD

**Issue by KevinBatdorf** [DavidAnderson684/simba-plugin-manager-updater#9] opened 2020-09-03 04:41 UTC
https://github.com/DavidAnderson684/simba-plugin-manager-updater/blob/5acf320faa661ebfd275709bd3088d8c7f089d76/class-udm-updater.php#L719

Hey David,

One user is reporting this

```
[Wed Sep 02 08:56:12.697457 2020] [:error] [pid 359330:tid 139711939032832] [client 23.16.24.245:49840] PHP Fatal error: Can't use method return value in write context in /home/username/public_html/wp-content/plugins/ml-slider-pro/vendor/davidanderson684/simba-plugin-manager-updater/class-udm-updater.php on line 719
[Wed Sep 02 08:56:05.767539 2020] [:error] [pid 359392:tid 139711980992256] [client 23.16.24.245:49835] PHP Fatal error: Can't use method return value in write context in /home/username/public_html/wp-content/plugins/ml-slider-pro/vendor/davidanderson684/simba-plugin-manager-updater/class-udm-updater.php on line 719, referer: https://username.com/wp-admin/plugins.php
[Wed Sep 02 08:56:05.163491 2020] [:error] [pid 359330:tid 139711980992256] [client 23.16.24.245:49834] PHP Fatal error: Can't use method return value in write context in /home/username/public_html/wp-content/plugins/ml-slider-pro/vendor/davidanderson684/simba-plugin-manager-updater/class-udm-updater.php on line 719, referer: https://username.com/wp-admin/plugins.php
[Wed Sep 02 08:55:55.261911 2020] [:error] [pid 359330:tid 139712022951680] [client 23.16.24.245:49832] PHP Warning: call_user_func() expects parameter 1 to be a valid callback, class 'Puc_v4p7_Plugin_Info' not found in /home/username/public_html/wp-content/plugins/ml-slider-pro/vendor/yahnis-elsts/plugin-update-checker/Puc/v4p7/UpdateChecker.php on line 610, referer: https://username.com/wp-admin/plugins.php
[Wed Sep 02 08:55:53.681445 2020] [:error] [pid 359393:tid 139711960012544] [client 159.203.98.228:52750] PHP Fatal error: Can't use method return value in write context in /home/username/public_html/wp-content/plugins/ml-slider-pro/vendor/davidanderson684/simba-plugin-manager-updater/class-udm-updater.php on line 719
```

Google suggests it's to do with using `empty()` here.

https://www.google.com/search?q=Can%27t+use+method+return+value+in+write+context&oq=Can%27t+use+method+return+value+in+write+context&aqs=chrome..69i57j69i59j69i60&sourceid=chrome&ie=UTF-8

Additionally, the user included their info:
<img width="399" alt="Screen-Shot-2020-09-02-at-10-18-54-AM" src="https://user-images.githubusercontent.com/1478421/92071943-4422b480-edda-11ea-9fa3-57f1c50a3286.png">

I could probably prepare a PR but not exactly sure how to test it properly. Let me know.

**Comment by DavidAnderson684** [comment] 2020-09-03 09:28
`yahnis-elsts/plugin-update-checker/Puc/v4p7/UpdateChecker.php`

That's old; currently release series is v4p10. So, the first thing he should do is update (4p8 was released October 2019 - https://github.com/YahnisElsts/plugin-update-checker/releases). I'll close the issue - re-open if the problem is still there!

**Closed by DavidAnderson684** 2020-09-03 09:28 UTC

**Comment by KevinBatdorf** [comment] 2020-09-03 10:06
@DavidAnderson684 Looking into it further, the issue is actually from using `empty()` on a function instead of a variable. But it seems that functionality was added in PHP5.5. 

This line from this package (not yahnis-elsts' package):
```
if (!empty($this->get_plugin_data('PluginURI')))
```

https://www.php.net/manual/en/function.empty.php
<img width="680" alt="Screen Shot 2020-09-03 at 5 04 52 PM" src="https://user-images.githubusercontent.com/1478421/92101633-9af2b300-ee07-11ea-9557-2704613b95c3.png">

**Comment by DavidAnderson684** [comment] 2020-09-03 20:58
So, all this time every project using this library has had a secret requirement for PHP 5.5+ - and this is apparently the first time it's come to light.

The empty() is unnecessary, so I've made a commit to remove it, and will immediately afterwards push out a new release.
